spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC&characterEncoding=UTF-8
        username: postgres
        password: 1234
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true

logging:
    level:
        org.hibernate.SQL: debug

server:
    servlet:
        context-path: /example
    port: 80